### PR TITLE
fix vite deprecation warning

### PR DESCRIPTION
**Pull request by Lenni009**

### CODE REVIEW

**Comment by Khaoz-Topsy** [comment]
I am going to use a custom domain name for the site, so no need for the base path 😋

**Comment by Lenni009** [comment]
PR updated

**Comment by Khaoz-Topsy** [comment]
Why you so fast on this little throw away github pages site 😂

**Comment by Lenni009** [comment]
Unemployed and not motivated to work through the huge wiki backlog I guess 😛

**Pull request merged**
